import React from 'react'

function Statistics() {
  return (
    <div>
        <h2 className='quad-head'>Statistics</h2>
        <div className='table-div'>
            <table>
                <tbody>
                    <tr>
                        <th>One</th>
                        <th>Two</th>
                        <th>Three</th>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                    <tr>
                        <td>one</td>
                        <td>two</td>
                        <td>three</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
  )
}

export default Statistics